### ISSUE TITLE
Sending syscoin doesn't actually send from "current alias", draws inputs from wherever possible rather than selected alias

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#135]
Switching from all aliases to a difference alias does not actually send Syscoin from that alias
Repro step:
- have multiple aliases
- switch to a different alias from "All Aliases"; preferrably not the first one on the dropdown list
- send syscoin to any address from the send/receive tab
- restart BM (due to bug #134 )
- the dropdown list will show that the coin was withdrawn from another alias (in my case, the first alias on the list)

**Comment by sidhujag** [comment]
Core 2.2 should fix

**Comment by dwasyluk** [comment]
@sidhujag does one use aliaspay for this or how does one send SYS from an alias (even in 2.2)? Curious since `sendtoaddress` the command we currently use doesn't take any inputs other than destination address and amount (unless you go into coin-control like things). In 2.2 will there be an optional `fromAlias` or something? If not specified use any inputs that don't belong to an alias, something like that?

**Comment by sidhujag** [comment]
Yes in 2.2 you will always be selecting an alias to do payments from. I guess if you select "wallet" or something it will go through sendcoins but otherwise it should call aliaspay which will properly deduct balances and add balances to any aliases your sending to.

**Comment by jnessbcf** [comment]
Alias pay now exists in BMD 3.0.
