### ISSUE TITLE
"All Aliases" balance/text misleading

### ISSUE THREAD

**Issue by willyko** [syscoin/blockmarket-desktop-public#166]
![screen shot 2017-06-28 at 2 01 36 pm](https://user-images.githubusercontent.com/11524904/27660008-6168feb0-5c0a-11e7-9cfa-661371a09f40.png)

I think this is because coins in the default receiving address is not listed in the dropdown.  This may confuse people though.

@Dwasyluk edit: This is correct "All Aliases" is really "All non alias inputs". We need to change the label to something more meaningful and add a tooltip to express this, but ultimately the aliases will never add up to this entry (just to be clear).

**Comment by dwasyluk** [comment]
They will never sum to all aliases as "All Aliases" is really "Total in All Addresses". We already have an item to change the label and add contextual tooltip help for clarity. Closing this as the list will never sum to "All Aliases" since that's not how the construct works. "All Aliases" is simply a another name for "all inputs not owned by an alias", to which Alias balances will never sum. The fix here is just a wording change.

**Comment by dwasyluk** [comment]
Reopening under a more focused scope.
