### ISSUE TITLE
Password with some special characters will not work

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#231]
If you try and set a password in BM with a special characters the wallet just hangs and does nothing. If you try and set the same password through the console you get an error. Also if your password from QT contains characters you cannot unlock either through BM or console. I will DM Sid further details

**Comment by johnp1954** [comment]
Any update on this issue

**Comment by einalex** [comment]
you can escape those special characters on the console (shell/terminal/cli) by putting \ before them. might also work in BM.

**Comment by einalex** [comment]
from within python you need to put to \ before them...that might also translate to BM

**Comment by einalex** [comment]
You can escape those special characters on the console (shell/terminal/cli) by putting \ before them. This might also work in BM.
From within python you need to put two \ before them...that might also translate to BM

**Comment by dwasyluk** [comment]
@johnp1954 @einalex what password are you using exactly to cause this problem? And this is the WALLET password right- not an alias password (just to be clear)? I just tried encrypting a clean wallet with pw `test*/!` and encrypt and decrypt worked. Now when i encrypted i didnt get a clear message saying encrypt success, shut down and reopen, but the encryption worked and after restarting i was able to unlock the wallet. Can you let me know an exact pw string that is failing for you and also confirm its failing in the initial encryptwallet phase?

**Comment by dwasyluk** [comment]
I'm marking this as both needs-retest and ready for internal testing because the encoding may have been implicitly fixed by the conversion of the API used here from GET to POST. This isn't available in a binary build yet but if you can give me a string that fails in 1.0 and I can verify it works in 1.0.2-dev that'd do it 👍

**Comment by johnp1954** [comment]
Your example does work however it shouldn't have as it is less then 10 characters. If you try Test!"£$%^&*() is does not work

**Comment by dwasyluk** [comment]
Perfect thanks for that sample failing string, exactly what I needed.
You're not supposed to use <10characters but it does work via direct rpc.


On Sep 24, 2017 10:23 AM, "johnp1954" <notifications@github.com> wrote:

Your example does work however it shouldn't have as it is less then 10
characters. If you try Test!"£$%^&*() is does not work

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/syscoin/blockmarket-desktop-public/issues/231#issuecomment-331713364>,
or mute the thread

**Comment by johnp1954** [comment]
Less than 10 also works in BM

**Comment by dwasyluk** [comment]
Because BM uses RPC; the less than 10 part is not a bug. Syscoin follows
the same spec as Bitcoin core in that respect.

**Comment by dwasyluk** [comment]
Updated this for retest, it fixes one issue but may introduce another. Normal `\` escaping did not work in this case so blockmarket stores new wallet passwords with special characters by encoding those characters. This works fine for BM but presents issues if you try to unlock through syscoin-cli or QT you get an error (IF you're using a certain subset of special characters in your PW) because the actual PW is encoded. For example in a new wallet thru BM the PW `Test!"£$%^&*()` becomes `Test!&#xA3;$%^&#x26;*()`. BM knows how to handle this as does teh API but raw CLI will have issues. Maybe we could add an API function just to get the encoded PW like `getrawpassphrase` and it takes the passphrase (`Test!"£$%^&*()`) and returns the encoded pw (`Test!&#xA3;$%^&#x26;*()`) for use w CLI/QT.

**Comment by dwasyluk** [comment]
After deeper investigation this is a problem with the core bitcoin RPC it seems. Although these characters pose no problem via QT, QT-console, or syscoin-cli, they do not work when trying the RPC directly.

You can validate this hypothesis by calling the core RPC directly using CURL, you get the same "Parse Error" that I'm running into at higher levels, this is the curl command:
` curl --user u:p --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"encryptwallet","params":[\"£\"]}' -H 'content-type:text/plain;' http://127.0.0.1:8336`

and what i get in response is:

`{"result":null,"error":{"code":-32700,"message":"Parse error"},"id":null}`

Same as what im getting when calling thru API. Additionally this error code is from the core code, it comes from here: https://github.com/bitcoin/bitcoin/blob/62f2d769e45043c1f262ed45babb70fe237ad2bb/src/rpc/protocol.h#L38

**Comment by willyko** [comment]
The curl command you posted doesn't work even with regular character sets for params
`curl --user u:p --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"encryptwallet","params":[\"adsf\"]}' -H 'content-type:text/plain;' http://127.0.0.1:8002` 
gave me the same response:
`{"result":null,"error":{"code":-32700,"message":"Parse error"},"id":null}`

If you remove the escape for the double quotes then they both work
`curl --user u:p --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"encryptwallet","params":["£"]}' -H 'content-type:text/plain;' http://127.0.0.1:8002`
`curl --user u:p --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"encryptwallet","params":["asdf"]}' -H 'content-type:text/plain;' http://127.0.0.1:8002`

**Comment by dwasyluk** [comment]
Yea, the current request is being sent completely UNescaped- exactly like the second stanza in your reply (which works, confirmed). @sidhujag is going to add some debug output in the core to see why using the jsonrpc, which passes the _exact_ same value from all debugging points accessible to the team, yeilds a parse error (core error code -32700). 

I suspect there is some kind of transformation happening that we aren't seeing and with the proper debug code in the core RPC, we'll see the string difference when using `curl` vs `json rpc via nodejs` and be able to draw some solid conclusions on what needs to be done to fix the nodejs side.

**Comment by willyko** [comment]
Just to confirm... `json rpc via nodejs` resolves into a `curl` call in the end right? as shown when executing functions in Blockmarket console

**Comment by dwasyluk** [comment]
@willyko nice debugging on this one, this fix is now implemented and ready for internal retest.

**Comment by johnp1954** [comment]
This now works :-)

**Comment by pawwis29** [comment]
I dowloaded BM and I want to encrypt my wallet but i noticed i had some special characters in my password like * and ! how can I type my password correct ? Because I can't login to my account at the moment. 
I need to put something in the console ? 

Thanks for help !

**Comment by joeyb333** [comment]
I have the same issue as pawwis29. When I created this wallet on BM last November 2017, I was able to enter my password with a *. Now I cannot unlock my wallet and create an alias and use the platform. I see my funds in my wallet. Any help would be greatly appreciated. This is very frustrating.

**Comment by Zoltaneusz** [comment]
I think this problem still persists. I cannot unlock my wallet with some special characters in it. (E.g. <>#&@;:?éáűőúüö)
The wallet is still on the syscoin 2 chain and I tried unlocking with BM 1.1.4, .1.2.0, 1.2.1, 1.2.3, QT 2.1.4, 2.1.6. Of course with the backup wallet.dat always...
