### ISSUE TITLE
Block Market V1.1.1. Stuck on loading screen

### ISSUE THREAD

**Issue by Madland12** [syscoin/blockmarket-desktop-public#267]
I loaded Block Market version 1.1.1. and it worked for about 2 hours. Now it gets stuck on the Loading Screen. Is there a fix for this condition. I am running Windows 10 operating system.

**Comment by peteralexander25** [comment]
did you fix this?

**Comment by Madland12** [comment]
No I have not resolved this. I can not recover my original Wallet. The only
place I can see my original Wallet address is on Changelly in my
transaction history. I tried to back up my original Wallet and install It
in my new wallet and it said the transfer could not nlbe completed due to a
error. I am not sure what else to do. I am not sure that the wallet back up
I had was even a good back up.

**Comment by peteralexander25** [comment]
No I have not I get this error message is there a way to take my token out and send to another wallet ?

[image1.jpeg]

On 28 Nov 2017, at 02:14, Madland12 <notifications@github.com<mailto:notifications@github.com>> wrote:

No I have not resolved this. I can not recover my original Wallet. The only
place I can see my original Wallet address is on Changelly in my
transaction history. I tried to back up my original Wallet and install It
in my new wallet and it said the transfer could not nlbe completed due to a
error. I am not sure what else to do. I am not sure that the wallet back up
I had was even a good back up.

**Comment by Madland12** [comment]
So is there a way I can download a new wallet and put my original Wallet
address into it to transfer my coins?

**Comment by dwasyluk** [comment]
This is a duplicate of #264. Please continue the discussion there / track that issues progress to see when this is fixed. Currently slated for 1.1.3.
