### ISSUE TITLE
Sync progress percentage text cannot be seen when sync is 0-2% (confusing to new users)

### ISSUE THREAD

**Issue by bstr156** [syscoin/blockmarket-desktop-public#268]
A clearer initial indication of the sync process is warranted, especially in consideration of new users.  When sync is at 0-2% the figure cannot be seen clearly (white text against whitish background).  Users who are new or novice to blockchain are likely confused at the very beginning, staring at the screen for a good while wondering what (if anything) is going on.  For an improved first-impression, perhaps at least make the progress text more visible against the background, and/or have a separate text indicator like "Sync Status: Syncing/Synced", and an 'on hover' info bubble available with a full explanation, or a similar approach.

**Comment by JieHu8** [comment]
Can confirm. I'm new and confused that it was necessary to sync to the blockchain. Please improve this.

**Comment by dwasyluk** [comment]
There are several improvements in the scope of this fix:
* relocate progress bar from 'recent blocks' on homepage to persistent icon in notification bar. This icon is different than the others in that if you hover, it will open (rather than needing to click). The icon is a mini dynamic SVG that represents progress. The dropdown is the full progress bar as seen in recent blocks today but with improvements: 1) relocating the text to below the bar so it is clearly visible at all times, 2) making the text dark colored for better visibility, 3) adding a contextual help icon explaining what this all means.
* Sync progress modal- any time the wallet is opened and the sync progress is <100% a modal dialog opens with a large progress representation and a thorough explanation of what failing to let the wallet synchronize fully results in, and what syncing means, etc. The modal can be closed.

**Comment by doublesharp** [comment]
Show block connection status

<img width="316" alt="Please wait" src="https://user-images.githubusercontent.com/571472/36634452-a2f574a0-1959-11e8-8e63-074044396e05.png">
<img width="316" alt="Connecting to peers" src="https://user-images.githubusercontent.com/571472/36634414-300b0306-1959-11e8-8de5-4eb3183d8afd.png">
<img width="316" alt="Blocks loaded" src="https://user-images.githubusercontent.com/571472/36634456-b7110648-1959-11e8-987b-c52d6587d3c5.png">
