### ISSUE TITLE
Restore support for direct payments (Bitcoin, Zcash)

### ISSUE THREAD

**Issue by johnp1954** [syscoin/blockmarket-desktop-public#40]
When creating new offer and selecting theoption Syscoin,and Zcash then press create get an error 'Could not validate the payment options value'

**Comment by dwasyluk** [comment]
We removed all unsupported core features from BM and this is referring to the ability to select a payment option- SYS, ZEC, or BTC which we did have in initial betas. Since we don't have the "buy" side of that flow completed in BM we've removed it and hardcoded it to SYS-only for now, but will build a user-friendly experience for direct-ZEC and direct-BTC ASAP, targeting for 1.1.

**Comment by willyko** [comment]
Integrated payment processor will be in BM 1.2

**Comment by dwasyluk** [comment]
Direct payment support for BTC,SYS, or ZEC-only is now complete. #285 and #285 will be targeted for the next release and closely relate to this issue.
