### ISSUE TITLE
Set Blockmarket Navbar always on top

### ISSUE THREAD

**Issue by Keyare** [syscoin/blockmarket-desktop-public#71]
When browsing offers, top navbar scrolls with rest of page. I think the top navbar should be pinned to top so that navigation is always available.

**Comment by dwasyluk** [comment]
I disagree with this convention; ebay.com, etsy.com, github.com, the list goes on all do *not* stick the navbar to the top and i suggest w do the same, its a weird UI convention IMO that's why its not seen in many mainstream sites. If we choose to do this maybe because it feels more "app like" we should consider how it will be consistent in a mobile context and def target for post-final shortly thereafter.

**Comment by dwasyluk** [comment]
Closing as non-conventional for now.
